import Products from '@/components/home/Products'
import React from 'react'
export const metadata = {
    title: "Hero Kids",
    template: "%s | Hero Kids",
    description: "Generated by create next app",
};
const ProductsPage = () => {

    return (
        <Products />
    )
}

export default ProductsPage